number1=int(input("Введите первое число:"))
number2=int(input("Введите второе число:"))
number3=int(input("Введите третье число:"))
number4=int(input("Введите четвертое число:"))
print("Сумма чисел равна", number1+number2+number3+number4)